### PR TITLE
Helpers fccd nb0

### PR DESCRIPTION
**Pull request by ambarb**
just need to make these things import-able

stuck on how to make it aware of csx datastore without setting it 

improvements are definitely needed so please feel free to comment on the two modules

based on comments, will fix in place or or create issues for helpers.fccd.py and helpers.overscan.py

**### helpers.fccd.py**
- extract specific information about ROIs
- extract specific information about image shaping/concat, 
- dark searching (https://github.com/NSLS-II-CSX/csxtools/issues/55). -- bluesky darks needs significant development to be used blindly
- more simple functions to get 4D output as array

**### helpers.overscan.py**
- extracts overscan data if overscan =2 and not 0

### CODE REVIEW

**Comment by ambarb** [comment]
@hyperrealist do you want to also review? 

I need to make some minor change to propagate db into these functions

**Comment by hyperrealist** [comment]
@ambarb Of course, happy to review. But fair warning: I would benefit more than the code itself.

**Comment by ambarb** [comment]
fixed functions that need to make databroker calls without hard-coding inside the python module.  Thanks @mrakitin for the suggestion and the quick lesson on python `globals()`

This can be tested now.  Here is some sample code:

```python

from csxtools.helpers.fastccd import *

bgnd8, bgnd2, bgnd1 = get_dark_near_all(h, db=db)

if bgnd8 is not None:
    if bgnd1 is not None and bgnd2 is not None:
        darks_for_humans = [x.start["scan_id"] for x in [bgnd8, bgnd2, bgnd1]]
        print(f'Darks: {darks_for_humans}')
    elif bgnd1 is not None or bgnd2 is not None:
        darks_for_humans = [x.start["scan_id"] for x in [bgnd8, bgnd2, bgnd1] if x is not None ]
    else:
        darks_for_humans = [x.start["scan_id"] for x in [bgnd8, bgnd2, bgnd1] if x is not None ]
        print(f'Darks: {darks_for_humans}')
    darks_in_use = bgnd8, bgnd2, bgnd1
                            
else:
    darks_for_humans = [x.start["scan_id"] for x in [bgnd8, bgnd2, bgnd1] if x is not None ]
    darks_in_use = None
    logger.warning('NO DARK IMAGES, especially not autogain')

images = get_fastccd_images_sized(h, darks_in_use, flat=None)

```

This is fully ready for review, but I am leaving it in draft form for now.

**Comment by hyperrealist** [comment]
Here are some notes I took while reviewing `fastccd.py`.

NOTE: I am not yet fully informed about the complete context this code will operate at, though I tried to make no assumptions. But I am sure most of these comments are either non-issues or minor issues at worst, so please take everything I say with a speckle of NaCl.

- Function names use `fccd` and `fastccd` interchangeably. Not sure if they mean the same thing, and if so, whether the naming disparity is purposeful.
- `find_possible_darks()` will run into an unhandled exception at [this](https://github.com/NSLS-II-CSX/csxtools/blob/58ac9a9e9a1073d615dff981411234ee900c55f4/csxtools/helpers/fastccd.py#L67) line if `header.stop["exit_status"] == "abort"` since `exp_time` will not be defined in that case.
- I am not sure where [`db`](https://github.com/NSLS-II-CSX/csxtools/blob/58ac9a9e9a1073d615dff981411234ee900c55f4/csxtools/helpers/fastccd.py#L48) is defined in the scope (also referenced in `get_dark_near()`).
- Perhaps expected behavior, but `find_possible_darks()` may return a [pandas DataFrame here](https://github.com/NSLS-II-CSX/csxtools/blob/58ac9a9e9a1073d615dff981411234ee900c55f4/csxtools/helpers/fastccd.py#L70) _or_ a [python dictionary here](https://github.com/NSLS-II-CSX/csxtools/blob/58ac9a9e9a1073d615dff981411234ee900c55f4/csxtools/helpers/fastccd.py#L63) depending on the execution path.
- This may not be an issue, but `get_fastccd_flatfield()` may report an incorrect number of removed pixels _if_ original data already had `NaN`s.
- Could be improved (?): `header.table()` is called repeatedly near [this](https://github.com/NSLS-II-CSX/csxtools/blob/58ac9a9e9a1073d615dff981411234ee900c55f4/csxtools/helpers/fastccd.py#L199) line.
- Catch-all exceptions used [here](https://github.com/NSLS-II-CSX/csxtools/blob/58ac9a9e9a1073d615dff981411234ee900c55f4/csxtools/helpers/fastccd.py#L227) and [here](https://github.com/NSLS-II-CSX/csxtools/blob/58ac9a9e9a1073d615dff981411234ee900c55f4/csxtools/helpers/fastccd.py#L232). Perhaps you want to catch `KeyError` exceptions only?
- I am not sure what purpose `* 1` serves [here](https://github.com/NSLS-II-CSX/csxtools/blob/58ac9a9e9a1073d615dff981411234ee900c55f4/csxtools/helpers/fastccd.py#LL299C46-L299C48). If this is a python "trick" like `'123' * 1 === 123` in JavaScript, I'd suggest replacing it with a more readable implementation.
- Probably a non-issue but flagging anyway: [this](https://github.com/NSLS-II-CSX/csxtools/blob/58ac9a9e9a1073d615dff981411234ee900c55f4/csxtools/helpers/fastccd.py#L319) line will fail if `fccd_concat_params.rows == 'unknown'` _and_ `total_rows < 1000` since `leftstart` would be undefined in that case.
- You can _probably_ get rid of this [line](https://github.com/NSLS-II-CSX/csxtools/blob/58ac9a9e9a1073d615dff981411234ee900c55f4/csxtools/helpers/fastccd.py#L306) unless I am very much mistaken.
- If `get_images_scan` is ever called inside a larger script [this](https://github.com/NSLS-II-CSX/csxtools/blob/58ac9a9e9a1073d615dff981411234ee900c55f4/csxtools/helpers/fastccd.py#L350) warning message does not provide sufficient context to identify its meaning or origin.
- Minor: I think you are referring to `title` not `dark_gain` in the docstring [here](https://github.com/NSLS-II-CSX/csxtools/blob/58ac9a9e9a1073d615dff981411234ee900c55f4/csxtools/helpers/fastccd.py#LL16C5-L17C100)
- Minor: Typo: `contatenation` should be `concatenation` in the docstring [here](https://github.com/NSLS-II-CSX/csxtools/blob/58ac9a9e9a1073d615dff981411234ee900c55f4/csxtools/helpers/fastccd.py#LL240C39-L240C52)

I'll post my notes about `overscan.py` soon.

**Comment by ambarb** [comment]
@hyperrealist these functions are meant to be used in the context of the notebook found here https://github.com/ambarb/csx_workflow_fccd_auto

Regarding `db`, I didn't want to define that in these function since they can be used at any beamline using the fastCCD and bluesky, not just csx (or maybe we will have a second datastore for a second endstation).    @mrakitin advised against using python globals().   

There are really detailed notes so thank you so much.  

For the overscan module, that is just some really slow code I threw together to test overscan. If it proves useful, then it needs to be developed further, perhaps using a different approach or using C.

**Comment by ambarb** [comment]
note to andi : when merging go fix code for historical data (`scan = 82998`)

**Comment by ambarb** [comment]
@hyperrealist thank you so much for these comments.  the two remaining ones are quite in depth and I also need to make unit tests for this part.  

I will move these two leftovers to a new issue.

**Comment by ambarb** [comment]
@danielballan @cmazzoli any objections to merging?  None of this code touches existing code

**Pull request merged**
