### PR TITLE
Converted to force type change to uint16

### PR DESCRIPTION
**Pull request by stuwilkins**
Attn @ambarb and @danielballan 

This should fix some strangeness from the handler choosing if to return `uint16` or `int16`. This is currently untested.

### CODE REVIEW

**Comment by danielballan** [comment]
Verified that this fixes the issue. This fails on `master` and works on this branch:

```py
header = db[90720]
csxtools.get_fastccd_images(header)[0]
```

@stuwilkins @ambarb OK if I tag a release?

**Comment by danielballan** [comment]
Ah, thanks @stuwilkins I was just looking at the CI output.

**Comment by danielballan** [comment]
I'm taking the liberty of pushing some pretty aggressive changes to the CI harness here because it has bit rotted badly and is several years behind our current idea of best practices.

**Comment by danielballan** [comment]
Summary:

I manually tested @stuwilkins patch on CSX data, and it works. I addressed "bit rot" in the CI that was causing it to fail for reasons unrelated to the patch. I made a bunch of changes including:

* Use `flake8` instead of the (unmaintained) `pep8`.
* Make several style updates because `flake8` is stricter than `pep8` was.
* Use pip-based installation on Travis instead of conda-based installation from the abandoned `lightsource2-tag` channel.
* Add various `requirements*.txt` files and use them in `setup.py`.

**Comment by stuwilkins** [comment]
@danielballan this looks good, thank you! I am happy to now merge this.

**Pull request merged**
