### PR TITLE
Add image functions

### PR DESCRIPTION
**Pull request by stuwilkins**
Add useful image stack functions, this takes the mean of a nan stack of images

Attn @tacaswell @danielballan

### CODE REVIEW

**Comment by stuwilkins** [comment]
@tacaswell @danielballan 

Performance results on xf23id1-srv2

http://nbviewer.jupyter.org/gist/stuwilkins/8bcd1454ecc55737d062

**Comment by stuwilkins** [comment]
@danielballan the tests are failing because of `pims.pipeline` is there a new version externally for PIMS that fixes this so the tests build?

**Comment by danielballan** [comment]
As a workaround, add the soft-matter conda channel or just install with pip.

Also @ericdill could you update PIMS in lightsource2 channel?

**Comment by stuwilkins** [comment]
Thanks @danielballan I will wait for @ericdill to put on the correct channel. I have manually run the tests for this this time.

**Comment by stuwilkins** [comment]
Thanks to @ericdill we found some cyclic dependence with ``pims`` which is fixed in this PR.

**Comment by danielballan** [comment]
This looks good. Ready to merge?

**Comment by stuwilkins** [comment]
yes, looks good. Merging!

**Pull request merged**
