### PR TITLE
ENH : Added returned object as list of pipeline objects

### PR DESCRIPTION
**Pull request by stuwilkins**

### CODE REVIEW

**Comment by stuwilkins** [comment]
Attn : @ambarb @cmazzoli @wen-hu

**Comment by stuwilkins** [comment]
Ok, Please have a look @cmazzoli @ambarb and @wen-hu 
cc: @danielballan @tacaswell @stuartcambpell

This PR has rebuilt the `get_fastccd_images()` to account for changes in the `Databroker` and also adds the capability to:

- Use dask arrays to provide good lazy loading of images
- Allows for the searching backwards in time for correct dark images. This requires the metadata to be inserted into the measurement of dark images. @ambarb and I discussed this yesterday and we need a function at CSX to do the measurement. 
- Extracts overscan rows from the image and returns them. At this point we don't really know what to do with the overscan rows.

Some Questions:

- Given returning dask objects with different processes is time wise 0, I am wondering if we should return the background corrected and non background corrected versions of the data along with the background stack. 
- Should the returned object be a tuple such as `a, b, c = func()` or should we return a dictionary. (Curious on @danielballan, @tacaswell or @stuartcampbell collective views on this)

This also goes along with a PR to https://github.com/NSLS-II/databroker/pull/308 also, I will work on that now. 

Please get back to me as soon as you can as I would like to prototype over the w/e.

**Comment by ambarb** [comment]
@stuwilkins RE "return the background corrected and non background corrected versions", maybe leave this as an option, but the default will be corrected data?  

I also have some other questions:
* Once a dark image is found via surfing `md`, are you going to use `configuration_attrs` to verify exposure time and gain settings?  
* Should we add something to `configuration_attrs` in the startup files that looks at the state of the slow shutter so that you do not need to look at the baseline to confirm a dark image?
* Is your plan to return the OS data (dask object) in `get_fccd_images()` and then can decide how is the best way to use this data before adding another function to CSXtools explicitly for OS?
* If dark image scans are explicitly defined, will there be a check in place to at least warn the user if they are not using a dark image, the exposure time does not match the lights, and maybe the gain is incorrect?

**Comment by stuwilkins** [comment]
Thanks @ambarb!! Quick review appreciated!

Yes, I will add code to check fccd config (time) and will verify when you supply the dark headers.

I am not sure I like configurable output, so I wa thinking of using a dictionary. Let me try that and put up an example notebook......

**Comment by danielballan** [comment]
> Should the returned object be a tuple such as a, b, c = func() or should we return a dictionary. 

For more than two or three return values, I slightly prefer a dictionary especially if the results don't have an "obvious" (easy to guess) ordering.

**Comment by stuwilkins** [comment]
Attn @mpmdean

**Comment by stuwilkins** [comment]
Notebook for example:

https://gist.github.com/1788ae2f6d42e613d44a5bd02b83aa9f

**Comment by stuwilkins** [comment]
Thanks @danielballan we are in agreement, the latest functions now have 2 layers, there is `get_fastccd_images()` which returns a dask array of the corrected stack, and `get_fastccd_data()` which returns a dictionary of possible useful entities.

**Comment by mpmdean** [comment]
This looks nice. 
What do you think about having `get_fastccd_data() `  return the header associated with the light images within the dictionary?

I'm suggesting this because the user can then pass around the returned dictionary while retaining access to the metadata they might want/need. Since we're already passing around a dictionary, I think the upside to including the header outweigh the small complexity increase.

**Comment by stuwilkins** [comment]
@mpmdean thats a great idea. 

Here is an update after computing on srv3:

https://gist.github.com/bb21c8c628248cf5127fc00499f0f9cb

**Comment by danielballan** [comment]
:+1:

**Comment by ambarb** [comment]
@danielballan and @stuwilkins is this what you are looking for?  there is an example notebook.  If you copy it from the server, then you should be able to see the name of the conda environment.

**Comment by danielballan** [comment]
@ambarb Sorry, for the delay -- I missed this notification. This looks right. Seems like Travis is just failing on a style check.

**Comment by danielballan** [comment]
Travis passes. Coverage is not happy, but I would say that's a known issue, especially for the data-loading codepaths.

**Comment by danielballan** [comment]
This has a couple variable misspellings that create `NameError`. I think it also relies on [this reverted databroker PR](https://github.com/NSLS-II/databroker/commit/0608b5e611d5fdb131d50f08f912db6dc05225bb), which was reverted because it broke APIs that HXN used.

**Pull request merged**
