### PR TITLE
Perform unit tests in NSLS-II conda environments

### PR DESCRIPTION
**Pull request by padraic-shafer**
This PR adds a GitHub action to run unit tests in recent [NSLS-II conda environments](https://github.com/nsls2-conda-envs).
* To limit the number of tests (and the time they take) the conda environments are limited to only those specified in `recent-envs.yml`.
* Older conda environments listed in `legacy-envs.yml` can be run from the workflow defined in `legacy-conda-env-tests.yml`

[Unit tests currently pass in all 36 environments from 2023 + 2024](https://github.com/padraic-shafer/csxtools/actions/runs/9183958306/job/25255506043) without modifications, so long as two other recent PRs are merged into the test environment.
* https://github.com/NSLS-II-CSX/csxtools/pull/94
* https://github.com/NSLS-II-CSX/csxtools/pull/95

PRs #94, #95, #96 can be merged in any order.

### CODE REVIEW

**Comment by ambarb** [comment]
@padraic-shafer do you want a review or merge?

**Comment by padraic-shafer** [comment]
Yes, please.  If it looks good to you, please merge.

**Review by ambarb — APPROVED** [review]
@padraic-shafer this looks pretty standard.  I do hope there is a template for this that is in a custom nsls-ii cookie-cutter like thing.  Is that right, or was this a lot of custom work?

**Comment by ambarb** [comment]
I'll merge after i check the other one and then try to run the test suite "as a developer" to make sure I don't have questions. I followed instructions from skbeam.

**Pull request merged**
