### PR TITLE
Add legacy code from "pyspec" into csxtools

### PR DESCRIPTION
**Pull request by stuwilkins**

### CODE REVIEW

**Comment by stuwilkins** [comment]
@ambarb This adds the Princeton file reader if you need it.... Also @cmazzoli @ambarb this has an old ``diffractometer`` class that I created. I think this could be modified quickly to do the angles -> UB Matrix for the reciprocal space conversion in the absence of any support for reciprocal space in the NSLS-II software stack.

**Comment by tacaswell** [comment]
The princeton reader is in filestore https://github.com/NSLS-II/filestore/blob/master/filestore/readers/spe.py

**Comment by stuwilkins** [comment]
Ok can we get this installed for the expt starting Wednesday, we need this to get the UB matrix in as metadata so we can process the data after the fact. If not we would have to use this to calculate the UB from two known reflections.

**Comment by stuwilkins** [comment]
My memory is failing me in my old age!

**Pull request closed without merging**
